FROM nginx:latest

# Copiar el archivo de configuración de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Eliminar el archivo de configuración predeterminado de Nginx
RUN rm /etc/nginx/conf.d/default.conf
